[package]
name = "hhe3"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.18", features = ["derive"] }
rand = "0.8.5"
rust_lisp = "0.18.0"
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "1.0.64"
toml = "0.8.19"
